[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
async-rayon = "0.1.0"
bytemuck = "1.16.1"
color-eyre = "0.6.3"
common = { path = "../common" }
futures = "0.3"
num = "0.4.3"
rayon = "1.10.0"
