[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
color-eyre = "0.6.3"
common = { path = "../common" }
indoc = "2"
pyo3 = { version = "0.20", features = ["eyre", "auto-initialize"] }
pyo3-asyncio = "0.20.0"
tqdm = "0.7"
